DROP TABLE IF EXISTS users, items, bookings, requests, comments CASCADE;
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    user_id BIGINT,
    description VARCHAR NOT NULL,
    CONSTRAINT fk_requests_to_users FOREIGN KEY(user_id) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT,
    description VARCHAR NOT NULL,
    is_available BOOLEAN NOT NULL,
    url VARCHAR(1000),
    request_id BIGINT,
    CONSTRAINT fk_items_to_requests FOREIGN KEY(request_id) REFERENCES requests(id),
    CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT,
    user_id BIGINT,
    status ENUM('WAITING','APPROVED','REJECTED','CANCELLED'),
    CONSTRAINT fk_bookings_to_users FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_bookings_to_items FOREIGN KEY(item_id) REFERENCES items(id));

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    item_id BIGINT,
    user_id BIGINT,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_comments_to_users FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id) REFERENCES items(id));
